In [1]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6]])
np.concatenate((arr1,arr2),axis=0)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[3,4]])
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 3, 4]])

In [6]:
#vertical stack
arr3=np.array([1,2,3])
arr4=np.array([4,5,6])
np.vstack((arr3,arr4))

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#horizontal stack
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [8]:
#filter
import numpy as np
arr=np.array([1,2,3,4,5,6])
mask=arr>3
mask

array([False, False, False,  True,  True,  True])

In [9]:
arr[mask]

array([4, 5, 6])

In [10]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
(arr>2) & (arr<6)


array([False, False,  True,  True,  True, False])

In [11]:
arr[(arr>2) & (arr<6)]

array([3, 4, 5])

In [13]:
arr[(arr<=3) | (arr>5)]

array([1, 2, 3, 6])

In [14]:
#filtering 2d array
import numpy as np
matrix=np.array([
    [10,25,30],
    [30,40,50]
])
print("Values>20:",matrix[matrix>20])

Values>20: [25 30 30 40 50]


In [15]:
scores=np.array([85,92,78,88,95,72,89,94,68,90])
print("values>90:",scores[scores>90])

values>90: [92 95 94]


In [17]:
scores=np.array([85,92,78,88,95,72,89,94,68,90])
print("values between 70 to 80 are:",scores[(scores>70) & (scores<80)])

values between 70 to 80 are: [78 72]


In [19]:
num=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
even_num=num[num%2==0]
print("even numbers are:", even_num)

even numbers are: [ 2  4  6  8 10 12 14]


In [22]:
div_by_3 = num[num % 3 == 0]
print("Divisible by 3", div_by_3)

Divisible by 3 [ 3  6  9 12 15]


In [23]:
odd_num=num[num%2==0]
print("odd numbers are:", odd_num)

odd numbers are: [ 2  4  6  8 10 12 14]


In [30]:
import numpy as np
temp = np.array([22.5, 19.0, 25.6, 21.4, 29.9, 18.6, 23.1, 27.0])

print("Temperature above 24:", temp[temp > 24])
print("Temperature between 20 and 26:", temp[(temp > 20) & (temp < 26)])


Temperature above 24: [25.6 29.9 27. ]
Temperature between 20 and 26: [22.5 25.6 21.4 23.1]


In [31]:
prices=np.array([250,499,520,310,800,999,450,720])
print("prices above 500:", prices[prices > 500])

prices above 500: [520 800 999 720]
