In [1]:
import numpy as np
uniform=np.random.rand(3,3)
print("uniform Distribution",uniform)

uniform Distribution [[0.76176148 0.40456922 0.54641228]
 [0.06611556 0.20940049 0.46643696]
 [0.56719406 0.44834535 0.74715459]]


In [2]:
arr=np.array([1,2,3,4,5])
np.where(arr>3)

(array([3, 4], dtype=int64),)

In [3]:
print("Where > 3:", np.where(arr > 3))

Where > 3: (array([3, 4], dtype=int64),)


In [4]:
np.argmax(arr)

4

In [8]:
sorted_arr=np.array([1,3,5,7])
np.searchsorted(sorted_arr,6)

3

In [10]:
arr=np.array([1,2,3,4,5])
np.extract(arr>3,arr)

array([4, 5])

In [12]:
matrix=np.array([[1,2,3],[4,5,6]])
print("Original:\n",matrix)

Original:
 [[1 2 3]
 [4 5 6]]


In [13]:
print("Transposed :\n",np.transpose(matrix))

Transposed :
 [[1 4]
 [2 5]
 [3 6]]


In [14]:
#Mean Calculation
arr=np.array([1,2,3,4,5])
print("mean value: ",np.mean(arr))

mean value:  3.0


In [16]:
arr=np.array([1, 2, 3, 4, 5, 6])
np.split(arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [17]:
np.split(arr,[1,4])

[array([1]), array([2, 3, 4]), array([5, 6])]

In [18]:
matrix=np.array([[1,2,3],
                 [4,5,6]])
np.split(matrix,3,axis=1)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [20]:
np.split(matrix,2,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [22]:
arr=np.array([2,7,1,4,5])
print("Sorted copy :" ,np.sort(arr))

Sorted copy : [1 2 4 5 7]


In [23]:
matrix=np.array([[3,1,7],
                 [6,5,4]])
print("sorted Rows:\n", np.sort(matrix,axis=1))

sorted Rows:
 [[1 3 7]
 [4 5 6]]


In [25]:
print("sorted column:\n", np.sort(matrix,axis=0))

sorted Rows:
 [[3 1 4]
 [6 5 7]]
